"""
FAITH THROUGH PHYSICS — Folder Status Scanner
Scans all domain folders, checks which stages have content,
updates desktop.ini icons to reflect status.

Usage: python status_scan.py
       python status_scan.py --domain education

Icons:
  shell32.dll,4   = empty folder (yellow, nothing here)
  shell32.dll,46  = has content (blue star, work in progress)  
  shell32.dll,144 = complete (green checkmark, all checklist items done)

Also generates a status report showing completion per domain.
"""
import os
import glob
import sys

canonical = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Skip system folders
skip = ['_template', '_scripts', '_docs', '_meta', '_working',
        '90_data_inventory', '91_pipelines_nlp', '92_exports_handoffs']

ICON_EMPTY = '%SystemRoot%\\\\system32\\\\shell32.dll,4'
ICON_WIP = '%SystemRoot%\\\\system32\\\\shell32.dll,46'
ICON_DONE = '%SystemRoot%\\\\system32\\\\shell32.dll,144'

def scan_stage(stage_path):
    """Returns: 'empty', 'wip', or 'done'"""
    files = [f for f in os.listdir(stage_path) 
             if f not in ('README.md', 'desktop.ini', 'Thumbs.db')
             and not f.startswith('.')]
    if not files:
        return 'empty'
    # Check if README checklist has all items checked
    readme = os.path.join(stage_path, 'README.md')
    if os.path.exists(readme):
        with open(readme, 'r', encoding='utf-8') as f:
            content = f.read()
        unchecked = content.count('- [ ]')
        if unchecked == 0 and '- [x]' in content:
            return 'done'
    return 'wip'

def update_icon(stage_path, status):
    ini_path = os.path.join(stage_path, 'desktop.ini')
    if status == 'empty':
        icon = ICON_EMPTY
    elif status == 'wip':
        icon = ICON_WIP
    else:
        icon = ICON_DONE
    with open(ini_path, 'w', encoding='utf-8') as f:
        f.write('[.ShellClassInfo]\n')
        f.write(f'IconResource={icon}\n')


target_domain = None
if len(sys.argv) > 2 and sys.argv[1] == '--domain':
    target_domain = sys.argv[2].lower()

report = []

for domain_name in sorted(os.listdir(canonical)):
    domain_path = os.path.join(canonical, domain_name)
    if not os.path.isdir(domain_path):
        continue
    if domain_name.lower() in skip or domain_name.startswith('_') or domain_name.startswith('9'):
        continue
    if target_domain and domain_name.lower() != target_domain:
        continue
    
    stages_status = {}
    for stage_name in sorted(os.listdir(domain_path)):
        stage_path = os.path.join(domain_path, stage_name)
        if not os.path.isdir(stage_path):
            continue
        status = scan_stage(stage_path)
        stages_status[stage_name] = status
        update_icon(stage_path, status)
    
    empty = sum(1 for s in stages_status.values() if s == 'empty')
    wip = sum(1 for s in stages_status.values() if s == 'wip')
    done = sum(1 for s in stages_status.values() if s == 'done')
    total = len(stages_status)
    
    bar = ''
    for stage_name in sorted(stages_status.keys()):
        s = stages_status[stage_name]
        if s == 'empty':
            bar += '.'
        elif s == 'wip':
            bar += '#'
        else:
            bar += '*'
    
    report.append(f'{domain_name:25s} [{bar}] empty:{empty} wip:{wip} done:{done}')

print('FAITH THROUGH PHYSICS — Domain Status Report')
print('=' * 60)
print(f'{"DOMAIN":25s} [00-13 stages]       STATUS')
print('-' * 60)
for line in report:
    print(line)
print('-' * 60)
print('Legend: . = empty  # = work in progress  * = complete')
print()

# Write report to file
report_path = os.path.join(canonical, '_docs', 'STATUS_REPORT.md')
with open(report_path, 'w', encoding='utf-8') as f:
    f.write('# Faith Through Physics — Domain Status Report\n\n')
    f.write('```\n')
    for line in report:
        f.write(line + '\n')
    f.write('```\n\n')
    f.write('Legend: `.` = empty | `#` = work in progress | `*` = complete\n')
    f.write(f'\nGenerated by status_scan.py\n')

print(f'Report saved to {report_path}')
